DROP TABLE COUNTRY;
DROP TABLE PROJECT;
DROP TABLE LOAN;


CREATE TABLE COUNTRY 
(
  COUNTRY_ID NUMBER NOT NULL 
, REGION_NAME VARCHAR2(64) 
, COUNTRY_NAME VARCHAR2(64) 
, LATITUDE REAL 
, LONGITUDE REAL 
);

CREATE TABLE PROJECT 
(
  PROJECT_ID NUMBER NOT NULL 
, COUNTRY_ID NUMBER NOT NULL 
, PROJECT_NAME VARCHAR2(128) 
, URL VARCHAR2(256) 
, CLOSING_DATE DATE 
);

CREATE TABLE LOAN 
(
  LOAN_ID NUMBER NOT NULL 
, PROJECT_ID NUMBER NOT NULL 
, STATUS VARCHAR2(20) 
, AMOUNT NUMBER 
, BOARD_APPROVAL_DATE DATE 
);

ALTER TABLE COUNTRY
	ADD CONSTRAINT COUNTRY_PK PRIMARY KEY(COUNTRY_ID);

ALTER TABLE PROJECT
	ADD CONSTRAINT PROJECT_PK PRIMARY KEY(PROJECT_ID);
ALTER TABLE PROJECT
	ADD CONSTRAINT COUNTRY_FK
		FOREIGN KEY (COUNTRY_ID)
		REFERENCES COUNTRY(COUNTRY_ID);
		
ALTER TABLE LOAN
	ADD CONSTRAINT LOAN_PK PRIMARY KEY(LOAN_ID);
ALTER TABLE LOAN
	ADD CONSTRAINT PROJECT_FK
		FOREIGN KEY (PROJECT_ID)
		REFERENCES PROJECT(PROJECT_ID);