SELECT 
          COUNTRY.COUNTRY_NAME
         ,SUM(AMOUNT)
FROM PROJECT 
            INNER JOIN LOAN ON LOAN.PROJECT_ID = PROJECT.PROJECT_ID
            INNER JOIN COUNTRY ON COUNTRY.COUNTRY_ID = PROJECT.COUNTRY_ID
GROUP BY COUNTRY.COUNTRY_NAME
ORDER BY SUM(AMOUNT) DESC
