DROP TABLE COUNTRY_PROJECT_BRIDGE;
DROP TABLE PROJECT_LOAN_BRIDGE;
DROP TABLE PROJECT;
DROP TABLE COUNTRY;
DROP TABLE REGION;
DROP TABLE LOAN;

CREATE TABLE REGION
(
    REGION_ID NUMBER NOT NULL
,	REGION_NAME VARCHAR2(128) 
);


CREATE TABLE COUNTRY 
(
  COUNTRY_ID NUMBER NOT NULL 
, REGION_ID  NUMBER NOT NULL
, COUNTRY_NAME VARCHAR2(64) 
);

CREATE TABLE COUNTRY_PROJECT_BRIDGE
(
  COUNTRY_ID NUMBER NOT NULL 
, PROJECT_ID NUMBER NOT NULL
);


CREATE TABLE PROJECT 
(
  PROJECT_ID NUMBER NOT NULL 
, COUNTRY_ID NUMBER NOT NULL 
, PROJECT_NAME VARCHAR2(128) 
, CLOSING_DATE DATE 
);

CREATE TABLE PROJECT_LOAN_BRIDGE
(
  LOAN_ID NUMBER NOT NULL 
, PROJECT_ID NUMBER NOT NULL
);

CREATE TABLE LOAN 
(
  LOAN_ID NUMBER NOT NULL 
, STATUS VARCHAR2(20) 
, AMOUNT NUMBER 
, BOARD_APPROVAL_DATE DATE 
);


ALTER TABLE REGION
    ADD CONSTRAINT REGION_PK PRIMARY KEY(REGION_ID);


ALTER TABLE COUNTRY
	ADD CONSTRAINT COUNTRY_PK PRIMARY KEY(COUNTRY_ID);
ALTER TABLE COUNTRY
	ADD CONSTRAINT REGION_FK
		FOREIGN KEY (REGION_ID)
		REFERENCES REGION(REGION_ID);

		
ALTER TABLE PROJECT
	ADD CONSTRAINT PROJECT_PK PRIMARY KEY(PROJECT_ID);

		
ALTER TABLE LOAN
	ADD CONSTRAINT LOAN_PK PRIMARY KEY(LOAN_ID);

	
ALTER TABLE COUNTRY_PROJECT_BRIDGE
	ADD CONSTRAINT COUNTRY_PROJECT_BRIDGE_PK PRIMARY KEY(COUNTRY_ID, PROJECT_ID);
ALTER TABLE COUNTRY_PROJECT_BRIDGE
	ADD CONSTRAINT CPB_COUNTRY_FK
		FOREIGN KEY (COUNTRY_ID)
		REFERENCES COUNTRY(COUNTRY_ID);
ALTER TABLE COUNTRY_PROJECT_BRIDGE
	ADD CONSTRAINT CPB_PROJECT_FK
		FOREIGN KEY (PROJECT_ID)
		REFERENCES PROJECT(PROJECT_ID);

ALTER TABLE PROJECT_LOAN_BRIDGE
	ADD CONSTRAINT PROJECT_LOAN_BRIDGE_PK PRIMARY KEY(PROJECT_ID, LOAN_ID);
ALTER TABLE PROJECT_LOAN_BRIDGE
	ADD CONSTRAINT PLB_LOAN_FK
		FOREIGN KEY (LOAN_ID)
		REFERENCES LOAN(LOAN_ID);
ALTER TABLE PROJECT_LOAN_BRIDGE
	ADD CONSTRAINT PLB_PROJECT_FK
		FOREIGN KEY (PROJECT_ID)
		REFERENCES PROJECT(PROJECT_ID);