-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-25 00:12:55 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE country CASCADE CONSTRAINTS;

DROP TABLE countryprojectbridge CASCADE CONSTRAINTS;

DROP TABLE loan CASCADE CONSTRAINTS;

DROP TABLE project CASCADE CONSTRAINTS;

DROP TABLE projectloanbridge CASCADE CONSTRAINTS;

DROP TABLE region CASCADE CONSTRAINTS;

CREATE TABLE country (
    country_id     NUMBER(10) NOT NULL,
    country_name   VARCHAR2(128),
    region_id      NUMBER(10) NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_id );

CREATE TABLE countryprojectbridge (
    country_id   NUMBER(10) NOT NULL,
    project_id   NUMBER(10) NOT NULL
);

ALTER TABLE countryprojectbridge ADD CONSTRAINT countryprojectbridge_pk PRIMARY KEY ( country_id,
                                                                                      project_id );

CREATE TABLE loan (
    loan_id         NUMBER(10) NOT NULL,
    status          VARCHAR2(8),
    amount          INTEGER,
    approval_date   DATE
);

ALTER TABLE loan ADD CONSTRAINT loan_pk PRIMARY KEY ( loan_id );

CREATE TABLE project (
    project_id     NUMBER(10) NOT NULL,
    project_name   VARCHAR2(256),
    closing_date   DATE
);

ALTER TABLE project ADD CONSTRAINT project_pk PRIMARY KEY ( project_id );

CREATE TABLE projectloanbridge (
    project_id   NUMBER(10) NOT NULL,
    loan_id      NUMBER(10) NOT NULL
);

ALTER TABLE projectloanbridge ADD CONSTRAINT projectloanbridge_pk PRIMARY KEY ( project_id,
                                                                                loan_id );

CREATE TABLE region (
    region_name   VARCHAR2(96) NOT NULL,
    region_id     NUMBER(10) NOT NULL
);

ALTER TABLE region ADD CONSTRAINT region_pk PRIMARY KEY ( region_id );

ALTER TABLE country
    ADD CONSTRAINT country_region_fk FOREIGN KEY ( region_id )
        REFERENCES region ( region_id );
		
ALTER TABLE countryprojectbridge
    ADD CONSTRAINT cpbridge_country_fk FOREIGN KEY ( country_id )
        REFERENCES country ( country_id );

ALTER TABLE countryprojectbridge
    ADD CONSTRAINT cpbridge_project_fk FOREIGN KEY ( project_id )
        REFERENCES project ( project_id );

ALTER TABLE projectloanbridge
    ADD CONSTRAINT plbridge_loan_fk FOREIGN KEY ( loan_id )
        REFERENCES loan ( loan_id );

ALTER TABLE projectloanbridge
    ADD CONSTRAINT plbridge_project_fk FOREIGN KEY ( project_id )
        REFERENCES project ( project_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             0
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
